In [1]:
import numpy as np
import torch

In [2]:
torch.__version__

'1.5.0+cu101'

In [3]:
x = [1,2,3]
array = np.array(x)

In [4]:
print(array)

[1 2 3]


In [5]:
tensor = torch.tensor(x)
print(tensor)

tensor([1, 2, 3])


In [6]:
print(array.shape)
print(tensor.shape)

(3,)
torch.Size([3])


In [7]:
print(array.mean())

2.0


In [8]:
print(tensor.float().mean())

tensor(2.)


In [9]:
tensor = torch.randn((2,2))

In [10]:
print(tensor)

tensor([[-0.2309,  1.4306],
        [ 0.8977,  0.3054]])


In [11]:
print(tensor@tensor)

tensor([[1.3376, 0.1066],
        [0.0669, 1.3775]])


In [12]:
print((tensor@tensor).T)

tensor([[1.3376, 0.0669],
        [0.1066, 1.3775]])


In [13]:
tensor = torch.tensor([1,1,23])

In [14]:
tensor.view((3,1))

tensor([[ 1],
        [ 1],
        [23]])